task: detection

evaluator:
  type: CocoEvaluator
  iou_types: ['bbox', ]

num_classes: 2
remap_mscoco_category: False

train_dataloader:
  type: DataLoader
  dataset:
    type: CocoDetection
    img_folder: /data/D-FINE/dataset/images/train
    ann_file: /data/D-FINE/dataset/annotations/instances_train.json
    return_masks: False
    transforms:
      type: Compose
      ops:
        - type: RandomHorizontalFlip
          prob: 0.5
        - type: RandomPaddedCrop
          scale: [0.8, 1.2]
          prob: 0.5
        - type: Resize
          size: [640, 640]
          keep_ratio: True
        - type: PadToSize
          size: [640, 640]
          pad_value: 114.0
        - type: ToTensor
        - type: Normalize
          mean: [0.485, 0.456, 0.406]
          std: [0.229, 0.224, 0.225]
  shuffle: True
  num_workers: 4
  drop_last: True
  collate_fn:
    type: BatchImageCollateFunction

val_dataloader:
  type: DataLoader
  dataset:
    type: CocoDetection
    img_folder: /data/D-FINE/dataset/images/val
    ann_file: /data/D-FINE/dataset/annotations/instances_val.json
    return_masks: False
    transforms:
      type: Compose
      ops: ~
  shuffle: False
  num_workers: 2
  drop_last: False
  collate_fn:
    type: BatchImageCollateFunction
